/*
Figma API

Testing StylesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/oliveiracleidson/gen-figma-api"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_StylesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test StylesAPIService GetFileStyles", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileKey string

		resp, httpRes, err := apiClient.StylesAPI.GetFileStyles(context.Background(), fileKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StylesAPIService GetStyle", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var key string

		resp, httpRes, err := apiClient.StylesAPI.GetStyle(context.Background(), key).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StylesAPIService GetTeamStyles", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var teamId string

		resp, httpRes, err := apiClient.StylesAPI.GetTeamStyles(context.Background(), teamId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
