/*
Figma API

Testing CommentReactionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/oliveiracleidson/gen-figma-api"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_CommentReactionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CommentReactionsAPIService DeleteCommentReaction", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileKey string
		var commentId string

		resp, httpRes, err := apiClient.CommentReactionsAPI.DeleteCommentReaction(context.Background(), fileKey, commentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CommentReactionsAPIService GetCommentReactions", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileKey string
		var commentId string

		resp, httpRes, err := apiClient.CommentReactionsAPI.GetCommentReactions(context.Background(), fileKey, commentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CommentReactionsAPIService PostCommentReaction", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileKey string
		var commentId string

		resp, httpRes, err := apiClient.CommentReactionsAPI.PostCommentReaction(context.Background(), fileKey, commentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
