/*
Figma API

Testing CommentsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/oliveiracleidson/gen-figma-api"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_CommentsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CommentsAPIService DeleteComment", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileKey string
		var commentId string

		resp, httpRes, err := apiClient.CommentsAPI.DeleteComment(context.Background(), fileKey, commentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CommentsAPIService GetComments", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileKey string

		resp, httpRes, err := apiClient.CommentsAPI.GetComments(context.Background(), fileKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CommentsAPIService PostComment", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileKey string

		resp, httpRes, err := apiClient.CommentsAPI.PostComment(context.Background(), fileKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
