/*
Figma API

This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).

API version: 0.20.0
Contact: support@figma.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the WebhookPingPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookPingPayload{}

// WebhookPingPayload struct for WebhookPingPayload
type WebhookPingPayload struct {
	// The passcode specified when the webhook was created, should match what was initially provided
	Passcode string `json:"passcode"`
	// UTC ISO 8601 timestamp of when the event was triggered.
	Timestamp time.Time `json:"timestamp"`
	// The id of the webhook that caused the callback
	WebhookId string `json:"webhook_id"`
	EventType string `json:"event_type"`
}

type _WebhookPingPayload WebhookPingPayload

// NewWebhookPingPayload instantiates a new WebhookPingPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookPingPayload(passcode string, timestamp time.Time, webhookId string, eventType string) *WebhookPingPayload {
	this := WebhookPingPayload{}
	this.Passcode = passcode
	this.Timestamp = timestamp
	this.WebhookId = webhookId
	this.EventType = eventType
	return &this
}

// NewWebhookPingPayloadWithDefaults instantiates a new WebhookPingPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookPingPayloadWithDefaults() *WebhookPingPayload {
	this := WebhookPingPayload{}
	return &this
}

// GetPasscode returns the Passcode field value
func (o *WebhookPingPayload) GetPasscode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Passcode
}

// GetPasscodeOk returns a tuple with the Passcode field value
// and a boolean to check if the value has been set.
func (o *WebhookPingPayload) GetPasscodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Passcode, true
}

// SetPasscode sets field value
func (o *WebhookPingPayload) SetPasscode(v string) {
	o.Passcode = v
}

// GetTimestamp returns the Timestamp field value
func (o *WebhookPingPayload) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *WebhookPingPayload) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *WebhookPingPayload) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetWebhookId returns the WebhookId field value
func (o *WebhookPingPayload) GetWebhookId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WebhookId
}

// GetWebhookIdOk returns a tuple with the WebhookId field value
// and a boolean to check if the value has been set.
func (o *WebhookPingPayload) GetWebhookIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WebhookId, true
}

// SetWebhookId sets field value
func (o *WebhookPingPayload) SetWebhookId(v string) {
	o.WebhookId = v
}

// GetEventType returns the EventType field value
func (o *WebhookPingPayload) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *WebhookPingPayload) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *WebhookPingPayload) SetEventType(v string) {
	o.EventType = v
}

func (o WebhookPingPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookPingPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["passcode"] = o.Passcode
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["webhook_id"] = o.WebhookId
	toSerialize["event_type"] = o.EventType
	return toSerialize, nil
}

func (o *WebhookPingPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"passcode",
		"timestamp",
		"webhook_id",
		"event_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookPingPayload := _WebhookPingPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookPingPayload)

	if err != nil {
		return err
	}

	*o = WebhookPingPayload(varWebhookPingPayload)

	return err
}

type NullableWebhookPingPayload struct {
	value *WebhookPingPayload
	isSet bool
}

func (v NullableWebhookPingPayload) Get() *WebhookPingPayload {
	return v.value
}

func (v *NullableWebhookPingPayload) Set(val *WebhookPingPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookPingPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookPingPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookPingPayload(val *WebhookPingPayload) *NullableWebhookPingPayload {
	return &NullableWebhookPingPayload{value: val, isSet: true}
}

func (v NullableWebhookPingPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookPingPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


