/*
Figma API

This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).

API version: 0.20.0
Contact: support@figma.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LibraryItemData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LibraryItemData{}

// LibraryItemData An object representing the library item information in the payload of the `LIBRARY_PUBLISH` event
type LibraryItemData struct {
	// Unique identifier for the library item
	Key string `json:"key"`
	// Name of the library item
	Name string `json:"name"`
}

type _LibraryItemData LibraryItemData

// NewLibraryItemData instantiates a new LibraryItemData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLibraryItemData(key string, name string) *LibraryItemData {
	this := LibraryItemData{}
	this.Key = key
	this.Name = name
	return &this
}

// NewLibraryItemDataWithDefaults instantiates a new LibraryItemData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLibraryItemDataWithDefaults() *LibraryItemData {
	this := LibraryItemData{}
	return &this
}

// GetKey returns the Key field value
func (o *LibraryItemData) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *LibraryItemData) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *LibraryItemData) SetKey(v string) {
	o.Key = v
}

// GetName returns the Name field value
func (o *LibraryItemData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LibraryItemData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LibraryItemData) SetName(v string) {
	o.Name = v
}

func (o LibraryItemData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LibraryItemData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *LibraryItemData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLibraryItemData := _LibraryItemData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLibraryItemData)

	if err != nil {
		return err
	}

	*o = LibraryItemData(varLibraryItemData)

	return err
}

type NullableLibraryItemData struct {
	value *LibraryItemData
	isSet bool
}

func (v NullableLibraryItemData) Get() *LibraryItemData {
	return v.value
}

func (v *NullableLibraryItemData) Set(val *LibraryItemData) {
	v.value = val
	v.isSet = true
}

func (v NullableLibraryItemData) IsSet() bool {
	return v.isSet
}

func (v *NullableLibraryItemData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLibraryItemData(val *LibraryItemData) *NullableLibraryItemData {
	return &NullableLibraryItemData{value: val, isSet: true}
}

func (v NullableLibraryItemData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLibraryItemData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


