/*
Figma API

This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).

API version: 0.20.0
Contact: support@figma.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LocalVariableCollectionModesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocalVariableCollectionModesInner{}

// LocalVariableCollectionModesInner struct for LocalVariableCollectionModesInner
type LocalVariableCollectionModesInner struct {
	// The unique identifier of this mode.
	ModeId string `json:"modeId"`
	// The name of this mode.
	Name string `json:"name"`
}

type _LocalVariableCollectionModesInner LocalVariableCollectionModesInner

// NewLocalVariableCollectionModesInner instantiates a new LocalVariableCollectionModesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocalVariableCollectionModesInner(modeId string, name string) *LocalVariableCollectionModesInner {
	this := LocalVariableCollectionModesInner{}
	this.ModeId = modeId
	this.Name = name
	return &this
}

// NewLocalVariableCollectionModesInnerWithDefaults instantiates a new LocalVariableCollectionModesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocalVariableCollectionModesInnerWithDefaults() *LocalVariableCollectionModesInner {
	this := LocalVariableCollectionModesInner{}
	return &this
}

// GetModeId returns the ModeId field value
func (o *LocalVariableCollectionModesInner) GetModeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ModeId
}

// GetModeIdOk returns a tuple with the ModeId field value
// and a boolean to check if the value has been set.
func (o *LocalVariableCollectionModesInner) GetModeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModeId, true
}

// SetModeId sets field value
func (o *LocalVariableCollectionModesInner) SetModeId(v string) {
	o.ModeId = v
}

// GetName returns the Name field value
func (o *LocalVariableCollectionModesInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LocalVariableCollectionModesInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LocalVariableCollectionModesInner) SetName(v string) {
	o.Name = v
}

func (o LocalVariableCollectionModesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocalVariableCollectionModesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["modeId"] = o.ModeId
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *LocalVariableCollectionModesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"modeId",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLocalVariableCollectionModesInner := _LocalVariableCollectionModesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLocalVariableCollectionModesInner)

	if err != nil {
		return err
	}

	*o = LocalVariableCollectionModesInner(varLocalVariableCollectionModesInner)

	return err
}

type NullableLocalVariableCollectionModesInner struct {
	value *LocalVariableCollectionModesInner
	isSet bool
}

func (v NullableLocalVariableCollectionModesInner) Get() *LocalVariableCollectionModesInner {
	return v.value
}

func (v *NullableLocalVariableCollectionModesInner) Set(val *LocalVariableCollectionModesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableLocalVariableCollectionModesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableLocalVariableCollectionModesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocalVariableCollectionModesInner(val *LocalVariableCollectionModesInner) *NullableLocalVariableCollectionModesInner {
	return &NullableLocalVariableCollectionModesInner{value: val, isSet: true}
}

func (v NullableLocalVariableCollectionModesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocalVariableCollectionModesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


