/*
Figma API

This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).

API version: 0.20.0
Contact: support@figma.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostCommentReactionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostCommentReactionRequest{}

// PostCommentReactionRequest struct for PostCommentReactionRequest
type PostCommentReactionRequest struct {
	// The emoji type of reaction as shortcode (e.g. `:heart:`, `:+1::skin-tone-2:`). The list of accepted emoji shortcodes can be found in [this file](https://raw.githubusercontent.com/missive/emoji-mart/main/packages/emoji-mart-data/sets/14/native.json) under the top-level emojis and aliases fields, with optional skin tone modifiers when applicable.
	Emoji string `json:"emoji"`
}

type _PostCommentReactionRequest PostCommentReactionRequest

// NewPostCommentReactionRequest instantiates a new PostCommentReactionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostCommentReactionRequest(emoji string) *PostCommentReactionRequest {
	this := PostCommentReactionRequest{}
	this.Emoji = emoji
	return &this
}

// NewPostCommentReactionRequestWithDefaults instantiates a new PostCommentReactionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostCommentReactionRequestWithDefaults() *PostCommentReactionRequest {
	this := PostCommentReactionRequest{}
	return &this
}

// GetEmoji returns the Emoji field value
func (o *PostCommentReactionRequest) GetEmoji() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Emoji
}

// GetEmojiOk returns a tuple with the Emoji field value
// and a boolean to check if the value has been set.
func (o *PostCommentReactionRequest) GetEmojiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Emoji, true
}

// SetEmoji sets field value
func (o *PostCommentReactionRequest) SetEmoji(v string) {
	o.Emoji = v
}

func (o PostCommentReactionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostCommentReactionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["emoji"] = o.Emoji
	return toSerialize, nil
}

func (o *PostCommentReactionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"emoji",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostCommentReactionRequest := _PostCommentReactionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostCommentReactionRequest)

	if err != nil {
		return err
	}

	*o = PostCommentReactionRequest(varPostCommentReactionRequest)

	return err
}

type NullablePostCommentReactionRequest struct {
	value *PostCommentReactionRequest
	isSet bool
}

func (v NullablePostCommentReactionRequest) Get() *PostCommentReactionRequest {
	return v.value
}

func (v *NullablePostCommentReactionRequest) Set(val *PostCommentReactionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostCommentReactionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostCommentReactionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostCommentReactionRequest(val *PostCommentReactionRequest) *NullablePostCommentReactionRequest {
	return &NullablePostCommentReactionRequest{value: val, isSet: true}
}

func (v NullablePostCommentReactionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostCommentReactionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


