/*
Figma API

This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).

API version: 0.20.0
Contact: support@figma.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// WebhookV2Status An enum representing the possible statuses you can set a webhook to: - `ACTIVE`: The webhook is healthy and receive all events - `PAUSED`: The webhook is paused and will not receive any events
type WebhookV2Status string

// List of WebhookV2Status
const (
	ACTIVE WebhookV2Status = "ACTIVE"
	PAUSED WebhookV2Status = "PAUSED"
)

// All allowed values of WebhookV2Status enum
var AllowedWebhookV2StatusEnumValues = []WebhookV2Status{
	"ACTIVE",
	"PAUSED",
}

func (v *WebhookV2Status) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := WebhookV2Status(value)
	for _, existing := range AllowedWebhookV2StatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid WebhookV2Status", value)
}

// NewWebhookV2StatusFromValue returns a pointer to a valid WebhookV2Status
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewWebhookV2StatusFromValue(v string) (*WebhookV2Status, error) {
	ev := WebhookV2Status(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for WebhookV2Status: valid values are %v", v, AllowedWebhookV2StatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v WebhookV2Status) IsValid() bool {
	for _, existing := range AllowedWebhookV2StatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to WebhookV2Status value
func (v WebhookV2Status) Ptr() *WebhookV2Status {
	return &v
}

type NullableWebhookV2Status struct {
	value *WebhookV2Status
	isSet bool
}

func (v NullableWebhookV2Status) Get() *WebhookV2Status {
	return v.value
}

func (v *NullableWebhookV2Status) Set(val *WebhookV2Status) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookV2Status) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookV2Status) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookV2Status(val *WebhookV2Status) *NullableWebhookV2Status {
	return &NullableWebhookV2Status{value: val, isSet: true}
}

func (v NullableWebhookV2Status) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookV2Status) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

