/*
Figma API

This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).

API version: 0.20.0
Contact: support@figma.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the WebhookV2ResponseInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookV2ResponseInfo{}

// WebhookV2ResponseInfo Information regarding the reply sent back from a webhook endpoint
type WebhookV2ResponseInfo struct {
	// HTTP status code of the response
	Status string `json:"status"`
	// UTC ISO 8601 timestamp of when the response was received
	ReceivedAt time.Time `json:"received_at"`
}

type _WebhookV2ResponseInfo WebhookV2ResponseInfo

// NewWebhookV2ResponseInfo instantiates a new WebhookV2ResponseInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookV2ResponseInfo(status string, receivedAt time.Time) *WebhookV2ResponseInfo {
	this := WebhookV2ResponseInfo{}
	this.Status = status
	this.ReceivedAt = receivedAt
	return &this
}

// NewWebhookV2ResponseInfoWithDefaults instantiates a new WebhookV2ResponseInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookV2ResponseInfoWithDefaults() *WebhookV2ResponseInfo {
	this := WebhookV2ResponseInfo{}
	return &this
}

// GetStatus returns the Status field value
func (o *WebhookV2ResponseInfo) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *WebhookV2ResponseInfo) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *WebhookV2ResponseInfo) SetStatus(v string) {
	o.Status = v
}

// GetReceivedAt returns the ReceivedAt field value
func (o *WebhookV2ResponseInfo) GetReceivedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ReceivedAt
}

// GetReceivedAtOk returns a tuple with the ReceivedAt field value
// and a boolean to check if the value has been set.
func (o *WebhookV2ResponseInfo) GetReceivedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReceivedAt, true
}

// SetReceivedAt sets field value
func (o *WebhookV2ResponseInfo) SetReceivedAt(v time.Time) {
	o.ReceivedAt = v
}

func (o WebhookV2ResponseInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookV2ResponseInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["received_at"] = o.ReceivedAt
	return toSerialize, nil
}

func (o *WebhookV2ResponseInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"received_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookV2ResponseInfo := _WebhookV2ResponseInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookV2ResponseInfo)

	if err != nil {
		return err
	}

	*o = WebhookV2ResponseInfo(varWebhookV2ResponseInfo)

	return err
}

type NullableWebhookV2ResponseInfo struct {
	value *WebhookV2ResponseInfo
	isSet bool
}

func (v NullableWebhookV2ResponseInfo) Get() *WebhookV2ResponseInfo {
	return v.value
}

func (v *NullableWebhookV2ResponseInfo) Set(val *WebhookV2ResponseInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookV2ResponseInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookV2ResponseInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookV2ResponseInfo(val *WebhookV2ResponseInfo) *NullableWebhookV2ResponseInfo {
	return &NullableWebhookV2ResponseInfo{value: val, isSet: true}
}

func (v NullableWebhookV2ResponseInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookV2ResponseInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


